### ISSUE TITLE
Script claims SQLite commands executed successfully, even when they didn't

### ISSUE THREAD

**Issue by MaienM** [indiscipline/nix-db-repair#2]
I forgot to run this as root at first, which caused the SQLite command to fail to do anything with the message `attempt to write a readonly database (8)`. The repair script just treated this as a success and attempted to then look for the next hash to fix, which resulted in the same hash as before and thus in an infinite loop.

The script should probably treat a failure of the `sqlite3` command as an error (assuming this command actually exist with a non-zero code in this case). Perhaps it should also verify that the database/hash to fix actually change.

**Comment by indiscipline** [comment]
Thanks a lot for the report!

Should be fixed with #[4fdabff](https://github.com/indiscipline/nix-db-repair/commit/4fdabff865085b551fa263cfd3679d526ab94dbc)
